const SUBJECTS = [
  { id: "physics",   label: "Physics",   blurb: "Motion, forces, energy, and the laws that govern them.", icon: "⚛" },
  { id: "chemistry", label: "Chemistry", blurb: "Atoms, bonds, reactions, and the matter around us.",     icon: "⚗" },
  { id: "biology",   label: "Biology",   blurb: "Cells, genetics, ecosystems, and the science of life.",  icon: "🧬" },
];

const DIFFICULTIES = [
  { id: "easy",   label: "Easy",   blurb: "Warm-up basics anyone can tackle." },
  { id: "medium", label: "Medium", blurb: "Solid recall and some reasoning."  },
  { id: "hard",   label: "Hard",   blurb: "Deeper concepts and trickier details." },
];

const PHYSICS = [
  /* ---------- EASY ---------- */
  { difficulty:"easy", q:"What is the SI unit of force?", options:["Joule","Newton","Watt","Pascal"], answer:"Newton", explanation:"Force is measured in newtons (N). One newton accelerates a 1 kg mass at 1 m/s²." },
  { difficulty:"easy", q:"What is the approximate acceleration due to gravity near Earth's surface?", options:["8.1 m/s²","9.8 m/s²","10.8 m/s²","11.2 m/s²"], answer:"9.8 m/s²", explanation:"Objects in free fall near Earth accelerate at about 9.8 m/s² downward, often rounded to 10 m/s² in calculations." },
  { difficulty:"easy", q:"What is the SI unit of electric current?", options:["Volt","Ohm","Ampere","Coulomb"], answer:"Ampere", explanation:"Current is measured in amperes (A) — one coulomb of charge passing a point per second." },
  { difficulty:"easy", q:"Which scientist published the law of universal gravitation?", options:["Galileo","Einstein","Newton","Kepler"], answer:"Newton", explanation:"Isaac Newton published the law of universal gravitation in his Principia Mathematica in 1687." },
  { difficulty:"easy", q:"Which of these quantities is a vector?", options:["Mass","Temperature","Velocity","Energy"], answer:"Velocity", explanation:"Velocity has both magnitude and direction, making it a vector. Speed alone has no direction and is scalar." },
  { difficulty:"easy", q:"What is the SI unit of energy?", options:["Newton","Watt","Pascal","Joule"], answer:"Joule", explanation:"Energy is measured in joules (J). One joule is the work done by a 1 N force acting over 1 m." },
  { difficulty:"easy", q:"A runner covers 200 m in 25 seconds. What is their average speed?", options:["4 m/s","6 m/s","8 m/s","25 m/s"], answer:"8 m/s", explanation:"Speed = Distance ÷ Time = 200 ÷ 25 = 8 m/s." },
  { difficulty:"easy", q:"You push a wall with 60 N and it does not move. How much force does the wall exert on you?", options:["0 N","30 N","60 N","120 N"], answer:"60 N", explanation:"Newton's third law: every action has an equal and opposite reaction. The wall pushes back with exactly 60 N." },
  { difficulty:"easy", q:"Why does ice float on liquid water?", options:["Ice has more molecules","Ice is less dense than liquid water","Ice is colder and rises","Ice molecules are heavier"], answer:"Ice is less dense than liquid water", explanation:"Water expands by about 9% when it freezes, making ice less dense than liquid water — an unusual property that is essential for aquatic life." },
  { difficulty:"easy", q:"A feather and a hammer are dropped at the same time on the Moon. Which lands first?", options:["The hammer — it is heavier","The feather — lighter objects fall faster","They land at the same time","The one dropped from higher up"], answer:"They land at the same time", explanation:"With no atmosphere on the Moon there is no air resistance. Both objects experience the same gravitational acceleration regardless of mass — as famously demonstrated on the Apollo 15 mission." },
  { difficulty:"easy", q:"What is inertia?", options:["The force that pulls objects down","The tendency of an object to resist any change in its motion","The speed of a moving object","The energy released during a collision"], answer:"The tendency of an object to resist any change in its motion", explanation:"Inertia is a property of mass described by Newton's first law: objects at rest stay at rest, and objects in motion stay in motion, unless acted on by an external force." },
  { difficulty:"easy", q:"What is the difference between speed and velocity?", options:["They are identical","Speed includes direction; velocity does not","Velocity includes direction; speed does not","Velocity is always larger"], answer:"Velocity includes direction; speed does not", explanation:"Speed is a scalar quantity (magnitude only). Velocity is a vector — it has both magnitude and direction. A car going 60 km/h north and one going 60 km/h south have the same speed but different velocities." },
  { difficulty:"easy", q:"Why does a seatbelt protect you in a sudden collision?", options:["It absorbs engine heat","It prevents Newton's first law from acting on your body","It applies Newton's first law — without it your body continues forward","It increases friction between you and the seat"], answer:"It applies Newton's first law — without it your body continues forward", explanation:"When a car stops suddenly, your body tends to keep moving forward at the car's original speed. The seatbelt provides the force needed to decelerate your body along with the car." },
  { difficulty:"easy", q:"What happens to the gravitational force between two objects if the distance between them is doubled?", options:["It doubles","It halves","It reduces to one quarter","It stays the same"], answer:"It reduces to one quarter", explanation:"Gravity follows an inverse-square law: F ∝ 1/r². If distance doubles, force becomes 1/2² = 1/4 of the original." },
  { difficulty:"easy", q:"Which state of matter transmits sound the fastest?", options:["Gas","Liquid","Solid","Sound speed is the same in all states"], answer:"Solid", explanation:"Sound travels as a pressure wave. Molecules in solids are tightly packed and strongly bonded, so vibrations are transmitted more efficiently — steel conducts sound about 15× faster than air." },
  { difficulty:"easy", q:"What does the speedometer in a car measure?", options:["Acceleration","Displacement","Speed","Velocity"], answer:"Speed", explanation:"A speedometer shows how fast the car is moving at a given moment (scalar magnitude) without indicating direction — so it measures speed, not velocity." },
  { difficulty:"easy", q:"A light bulb is rated at 60 W. What does this mean?", options:["It uses 60 joules of energy in total","It converts 60 joules of energy per second","It produces 60 newtons of force","It has a resistance of 60 ohms"], answer:"It converts 60 joules of energy per second", explanation:"Power is the rate of energy transfer. 60 W = 60 J/s, meaning the bulb converts 60 joules of electrical energy every second (mostly into heat and some light)." },
  { difficulty:"easy", q:"What type of energy does a compressed spring store?", options:["Kinetic energy","Thermal energy","Elastic potential energy","Chemical energy"], answer:"Elastic potential energy", explanation:"A compressed or stretched spring stores elastic potential energy, which converts to kinetic energy when released." },

  /* ---------- MEDIUM ---------- */
  { difficulty:"medium", q:"What is the speed of light in a vacuum?", options:["3 × 10⁶ m/s","3 × 10⁸ m/s","3 × 10¹⁰ m/s","3 × 10⁵ m/s"], answer:"3 × 10⁸ m/s", explanation:"Light travels at approximately 299,792,458 m/s in a vacuum — roughly 3 × 10⁸ m/s." },
  { difficulty:"medium", q:"Which law states that every action has an equal and opposite reaction?", options:["Newton's 1st law","Newton's 2nd law","Newton's 3rd law","Hooke's law"], answer:"Newton's 3rd law", explanation:"Newton's third law: for every action force there is an equal and opposite reaction force acting on a different object." },
  { difficulty:"medium", q:"Which type of wave does NOT require a medium to travel?", options:["Sound wave","Water wave","Electromagnetic wave","Seismic wave"], answer:"Electromagnetic wave", explanation:"EM waves (light, radio, X-rays) are self-propagating oscillations of electric and magnetic fields — they travel through a vacuum. Mechanical waves like sound need a medium." },
  { difficulty:"medium", q:"What does a converging (convex) lens do to parallel light rays?", options:["Spreads them out","Focuses them to a point","Reflects them back","Polarises them"], answer:"Focuses them to a point", explanation:"A convex lens bends parallel rays toward its focal point — the principle behind magnifying glasses, cameras, and the human eye." },
  { difficulty:"medium", q:"What does Einstein's equation E = mc² describe?", options:["Momentum of light","Kinetic energy","Mass-energy equivalence","Gravitational potential energy"], answer:"Mass-energy equivalence", explanation:"E = mc² shows that mass and energy are interchangeable. A tiny mass corresponds to an enormous amount of energy (c² ≈ 9 × 10¹⁶ m²/s²)." },
  { difficulty:"medium", q:"A 4 kg object accelerates at 6 m/s². What net force acts on it?", options:["0.67 N","10 N","24 N","48 N"], answer:"24 N", explanation:"Using Newton's second law: F = ma = 4 × 6 = 24 N." },
  { difficulty:"medium", q:"A large truck and a small car collide. Which experiences the greater impact force?", options:["The car — it is lighter","The truck — it is heavier","Both experience the same force","Whichever was moving faster"], answer:"Both experience the same force", explanation:"Newton's third law guarantees it: the force the car exerts on the truck is equal and opposite to the force the truck exerts on the car. The car's occupants suffer more because they decelerate faster (less mass)." },
  { difficulty:"medium", q:"Why does the sky appear blue?", options:["The atmosphere absorbs red light","The ocean reflects blue upward","Blue light has a short wavelength and scatters more through the atmosphere (Rayleigh scattering)","The sun emits mostly blue light"], answer:"Blue light has a short wavelength and scatters more through the atmosphere (Rayleigh scattering)", explanation:"Shorter wavelengths scatter more strongly. Blue light (≈450 nm) scatters in all directions as sunlight passes through air molecules, filling the sky with blue." },
  { difficulty:"medium", q:"A 6 kg object is at a height of 10 m. What is its gravitational potential energy? (g = 10 m/s²)", options:["16 J","60 J","600 J","6000 J"], answer:"600 J", explanation:"GPE = mgh = 6 × 10 × 10 = 600 J." },
  { difficulty:"medium", q:"An object moves in a perfect circle at constant speed. Is it accelerating?", options:["No — its speed is constant","Yes — its direction is constantly changing","Only at the top and bottom of the circle","Only if the circle is getting larger"], answer:"Yes — its direction is constantly changing", explanation:"Acceleration is a change in velocity, and velocity is a vector. Even at constant speed, changing direction means velocity changes — so there is centripetal acceleration pointing toward the centre." },
  { difficulty:"medium", q:"How do noise-cancelling headphones reduce sound?", options:["Dense foam blocks all frequencies","They generate a sound wave of opposite phase to cancel incoming noise","They absorb all sound electronically","They speed up the natural decay of sound waves"], answer:"They generate a sound wave of opposite phase to cancel incoming noise", explanation:"A microphone detects ambient noise; a speaker emits an equal but inverted wave. The two waves interfere destructively, cancelling the noise — this is called active noise cancellation." },
  { difficulty:"medium", q:"A ball is thrown horizontally at 15 m/s from a cliff. How far horizontally does it travel in 4 seconds? (Ignore air resistance)", options:["4 m","15 m","60 m","240 m"], answer:"60 m", explanation:"Horizontal and vertical motions are independent. Horizontal distance = speed × time = 15 × 4 = 60 m." },
  { difficulty:"medium", q:"A swimming pool appears shallower than it really is. What causes this?", options:["Water absorbs light reducing visible depth","Light bends (refracts) as it moves from water to air, shifting the apparent position of the bottom","Reflection on the surface reduces visibility","Light speeds up in water"], answer:"Light bends (refracts) as it moves from water to air, shifting the apparent position of the bottom", explanation:"When light exits the denser water into less-dense air, it bends away from the normal, making the bottom appear higher — typically a 2 m pool looks about 1.5 m deep." },
  { difficulty:"medium", q:"What is resonance in physics?", options:["Reflection of waves off a hard surface","Large-amplitude vibrations that build up when a driving frequency matches an object's natural frequency","The bending of waves around obstacles","Conversion of sound into light"], answer:"Large-amplitude vibrations that build up when a driving frequency matches an object's natural frequency", explanation:"Resonance can be useful (musical instruments, MRI machines) or destructive — it contributed to the Tacoma Narrows Bridge collapse in 1940." },
  { difficulty:"medium", q:"What is the difference between kinetic energy and potential energy?", options:["They are the same thing","KE is stored energy; PE is the energy of motion","KE is the energy of motion; PE is stored energy due to position or state","KE decreases as an object speeds up"], answer:"KE is the energy of motion; PE is stored energy due to position or state", explanation:"KE = ½mv². Gravitational PE = mgh. As a roller coaster descends, PE converts to KE — total mechanical energy is conserved (ignoring friction)." },
  { difficulty:"medium", q:"An elevator accelerates upward. What happens to your apparent weight?", options:["It decreases","It stays the same","It increases","It becomes zero"], answer:"It increases", explanation:"The floor must push harder on you to both support your weight and provide the upward net force for acceleration. The scale reads a higher normal force — you feel heavier." },
  { difficulty:"medium", q:"Why does sound travel faster in warm air than cold air?", options:["Warm air is denser","Warm air molecules move faster and transmit vibrations more quickly","Cold air absorbs sound","Warm air has lower pressure"], answer:"Warm air molecules move faster and transmit vibrations more quickly", explanation:"The speed of sound in air is approximately v = 331 + 0.6T m/s (T in °C). Higher temperature means faster molecular motion and quicker pressure wave propagation." },
  { difficulty:"medium", q:"What is the relationship between frequency and wavelength for a wave of fixed speed?", options:["They are directly proportional","They are inversely proportional","They are unrelated","They are always equal"], answer:"They are inversely proportional", explanation:"v = fλ. If wave speed is constant, doubling the frequency halves the wavelength — they are inversely proportional." },

  /* ---------- HARD ---------- */
  { difficulty:"hard", q:"Which principle explains why an aeroplane wing generates lift?", options:["Pascal's principle","Bernoulli's principle","Archimedes' principle","Doppler's principle"], answer:"Bernoulli's principle", explanation:"The curved upper surface of a wing makes air travel faster over it, reducing pressure above the wing (Bernoulli). The higher pressure beneath provides an upward lift force." },
  { difficulty:"hard", q:"What does the Heisenberg uncertainty principle state?", options:["Energy is always conserved","You cannot simultaneously know a particle's exact position and momentum","Waves and particles are the same","Time slows near massive objects"], answer:"You cannot simultaneously know a particle's exact position and momentum", explanation:"ΔxΔp ≥ ℏ/2. The more precisely you know a particle's position, the less precisely you can know its momentum — this is a fundamental property of nature, not a measurement limitation." },
  { difficulty:"hard", q:"What is the SI unit of magnetic flux?", options:["Tesla","Weber","Henry","Gauss"], answer:"Weber", explanation:"Magnetic flux is measured in webers (Wb). The tesla is flux density (Wb/m²). One weber = one volt-second." },
  { difficulty:"hard", q:"Which particle is the force carrier of the electromagnetic force?", options:["Gluon","Photon","W boson","Graviton"], answer:"Photon", explanation:"Virtual photons mediate the electromagnetic interaction between charged particles in quantum electrodynamics (QED)." },
  { difficulty:"hard", q:"What does entropy measure in thermodynamics?", options:["Heat capacity","The number of possible microscopic states (disorder) of a system","Pressure of a gas","Absolute temperature"], answer:"The number of possible microscopic states (disorder) of a system", explanation:"Entropy (S) quantifies disorder. The second law of thermodynamics states that total entropy of an isolated system always increases — this gives time its direction." },
  { difficulty:"hard", q:"A radioactive substance has a half-life of 20 years. What fraction of the original sample remains after 60 years?", options:["1/2","1/4","1/8","1/16"], answer:"1/8", explanation:"60 years = 3 half-lives. Remaining fraction = (1/2)³ = 1/8." },
  { difficulty:"hard", q:"A transformer has 200 primary turns and 1000 secondary turns. If the primary voltage is 50 V, what is the secondary voltage?", options:["10 V","50 V","250 V","500 V"], answer:"250 V", explanation:"Vs/Vp = Ns/Np → Vs = 50 × (1000/200) = 250 V. This is a step-up transformer." },
  { difficulty:"hard", q:"Why do GPS satellites require relativistic corrections to maintain accuracy?", options:["Their clocks wear out faster in space","Time runs slightly differently at high altitude (general relativity) and high speed (special relativity)","Signals travel faster in space","Earth's magnetic field slows radio signals"], answer:"Time runs slightly differently at high altitude (general relativity) and high speed (special relativity)", explanation:"Satellite clocks run fast due to weaker gravity (+45 µs/day) and slow due to orbital speed (−7 µs/day). Without corrections, GPS positions would drift by roughly 10 km per day." },
  { difficulty:"hard", q:"A rocket in deep space burns fuel at a constant rate. What happens to its acceleration over time?", options:["It decreases as fuel is exhausted","It remains constant","It increases as the rocket becomes lighter","It decreases because there is no friction"], answer:"It increases as the rocket becomes lighter", explanation:"F = ma. If thrust is constant but the rocket's mass decreases as fuel burns, a = F/m must increase. This is why rockets accelerate dramatically in their final burn stages." },
  { difficulty:"hard", q:"What distinguishes nuclear fission from nuclear fusion?", options:["Fission joins nuclei; fusion splits them","Fusion joins light nuclei; fission splits heavy nuclei","Both split nuclei at different temperatures","They are the same process at different scales"], answer:"Fusion joins light nuclei; fission splits heavy nuclei", explanation:"Fission: heavy nuclei (e.g. U-235) split into smaller fragments, releasing energy. Fusion: light nuclei (e.g. hydrogen isotopes) merge into heavier ones — the process powering the Sun and hydrogen bombs." },
  { difficulty:"hard", q:"What is the photoelectric effect, and why was it revolutionary?", options:["Light warms metals — explained by classical wave theory","Electrons are ejected from metal only above a threshold frequency, proving light is quantised (comes in packets)","Electrons slow down in metal and produce heat","X-rays are produced when electrons hit metal"], answer:"Electrons are ejected from metal only above a threshold frequency, proving light is quantised (comes in packets)", explanation:"Classical wave theory predicted intensity alone should eject electrons. Einstein showed light comes in quanta (photons) — only photons above a minimum energy (E = hf) can eject electrons. This earned Einstein the 1921 Nobel Prize." },
  { difficulty:"hard", q:"A wave travels at 340 m/s with a frequency of 680 Hz. What is its wavelength?", options:["0.2 m","0.5 m","2 m","5 m"], answer:"0.5 m", explanation:"v = fλ → λ = v/f = 340 ÷ 680 = 0.5 m." },
  { difficulty:"hard", q:"Why are high-voltage transmission lines used to carry electricity over long distances?", options:["To increase the current delivered to homes","To reduce energy lost as heat in the wires, since P = I²R and higher voltage means lower current","To reduce the weight of the cables","To prevent the lines from attracting lightning"], answer:"To reduce energy lost as heat in the wires, since P = I²R and higher voltage means lower current", explanation:"For the same power (P = IV), transmitting at high voltage requires low current. Since heat loss = I²R, halving the current reduces heat loss by a factor of four." },
  { difficulty:"hard", q:"An electron is accelerated through a potential difference of 100 V. What kinetic energy does it gain? (e = 1.6 × 10⁻¹⁹ C)", options:["1.6 × 10⁻²¹ J","1.6 × 10⁻¹⁹ J","1.6 × 10⁻¹⁷ J","1.6 × 10⁻¹⁵ J"], answer:"1.6 × 10⁻¹⁷ J", explanation:"KE = qV = 1.6 × 10⁻¹⁹ × 100 = 1.6 × 10⁻¹⁷ J." },
  { difficulty:"hard", q:"How does a microwave oven heat food?", options:["Infrared radiation heats the surface only","Microwaves cause water molecules to rotate rapidly, producing heat throughout the food","UV light breaks down molecular bonds","X-rays pass through uniformly heating all tissues"], answer:"Microwaves cause water molecules to rotate rapidly, producing heat throughout the food", explanation:"Microwaves at ~2.45 GHz cause polar water molecules to rapidly realign with the oscillating field. This molecular rotation generates heat — which is why dry foods with little water heat poorly." },
  { difficulty:"hard", q:"Does a photon have mass?", options:["Yes — because it has energy","No — photons have zero rest mass","Yes — but only when moving","Only when it collides with matter"], answer:"No — photons have zero rest mass", explanation:"Photons have zero rest mass, which is why they can travel at the speed of light. However, they carry momentum (p = E/c = hf/c), which is why radiation pressure can move solar sails." },
  { difficulty:"hard", q:"What is pair production in particle physics?", options:["Two protons fusing in a star","A high-energy photon creating an electron and a positron near a nucleus","A neutron splitting into a proton and electron","Two quarks combining to form a meson"], answer:"A high-energy photon creating an electron and a positron near a nucleus", explanation:"When a gamma ray with energy ≥ 1.022 MeV (2 × electron rest-mass energy) passes near a nucleus, it can convert entirely into an electron-positron pair — a direct demonstration of E = mc²." },
  { difficulty:"hard", q:"In a perfectly elastic collision, which quantities are conserved?", options:["Momentum only","Kinetic energy only","Both momentum and kinetic energy","Neither — energy is always lost"], answer:"Both momentum and kinetic energy", explanation:"In an elastic collision, no kinetic energy is lost to heat or deformation. Both total momentum and total kinetic energy are conserved. Billiard balls approximate this." },
];

const CHEMISTRY = [
  /* ---------- EASY ---------- */
  { difficulty:"easy", q:"What is the chemical symbol for Gold?", options:["Au","Ag","Gd","Go"], answer:"Au", explanation:"Au comes from the Latin 'aurum'. Gold has been known since antiquity and is element 79 on the periodic table." },
  { difficulty:"easy", q:"Which gas makes up most of Earth's atmosphere?", options:["Oxygen","Nitrogen","Carbon dioxide","Argon"], answer:"Nitrogen", explanation:"Nitrogen (N₂) accounts for about 78% of the atmosphere. Oxygen is about 21%, with argon and other gases making up the rest." },
  { difficulty:"easy", q:"What is the pH of pure water at 25°C?", options:["0","7","10","14"], answer:"7", explanation:"Pure water is neutral — equal concentrations of H⁺ and OH⁻ ions (1 × 10⁻⁷ mol/L each) give a pH of exactly 7." },
  { difficulty:"easy", q:"What is the chemical formula for table salt?", options:["KCl","NaCl","NaOH","CaCl₂"], answer:"NaCl", explanation:"Table salt is sodium chloride: Na⁺ (sodium) and Cl⁻ (chloride) ions held together by an ionic bond." },
  { difficulty:"easy", q:"Which subatomic particle has no electric charge?", options:["Proton","Electron","Neutron","Positron"], answer:"Neutron", explanation:"Neutrons are electrically neutral. Protons carry +1 charge, electrons −1. Neutrons reside in the nucleus alongside protons." },
  { difficulty:"easy", q:"Is burning a piece of wood a physical or chemical change?", options:["Physical — the wood only changes shape","Chemical — new substances (ash, CO₂, water vapour) are formed","Physical — you can reverse it by cooling","Neither — it is a nuclear change"], answer:"Chemical — new substances (ash, CO₂, water vapour) are formed", explanation:"A chemical change produces new substances. Burning (combustion) converts wood into ash, carbon dioxide, and water — substances with completely different properties that cannot easily be turned back into wood." },
  { difficulty:"easy", q:"What happens to the mass of iron when it rusts?", options:["It decreases","It stays the same","It increases","It becomes zero"], answer:"It increases", explanation:"Rusting is oxidation: iron reacts with oxygen from the air to form iron oxide (Fe₂O₃). The iron gains oxygen atoms, so the total mass increases — this is why a rusty car panel is heavier than a clean one." },
  { difficulty:"easy", q:"Which of the following is NOT a pure substance?", options:["Diamond","Gold","Oxygen gas","Salt water"], answer:"Salt water", explanation:"A pure substance has a fixed composition throughout. Salt water is a mixture (varying amounts of NaCl in water) — its composition depends on how much salt was added." },
  { difficulty:"easy", q:"What is an isotope?", options:["An atom with the same number of neutrons as protons","An atom of the same element with a different number of neutrons","A negatively charged ion","An atom that has lost an electron"], answer:"An atom of the same element with a different number of neutrons", explanation:"Isotopes have the same number of protons (same element) but different numbers of neutrons. Carbon-12 and Carbon-14 are both carbon, but C-14 has two extra neutrons and is radioactive." },
  { difficulty:"easy", q:"What does the atomic number of an element represent?", options:["Number of neutrons","Number of protons","Atomic mass","Number of electrons in the outer shell"], answer:"Number of protons", explanation:"The atomic number is the number of protons in the nucleus, which defines the element. Carbon always has 6 protons — change that and it becomes a different element." },
  { difficulty:"easy", q:"Which state of matter has a definite volume but no definite shape?", options:["Solid","Liquid","Gas","Plasma"], answer:"Liquid", explanation:"Liquids maintain a fixed volume but take the shape of their container. Solids have fixed shape and volume; gases have neither." },
  { difficulty:"easy", q:"What is the chemical formula for water?", options:["HO","H₂O","H₂O₂","OH₂"], answer:"H₂O", explanation:"Each water molecule consists of two hydrogen atoms bonded to one oxygen atom. H₂O₂ is hydrogen peroxide — a completely different substance." },
  { difficulty:"easy", q:"Which particle determines the chemical behaviour of an atom?", options:["Protons","Neutrons","Electrons","Nucleus as a whole"], answer:"Electrons", explanation:"Chemical reactions involve the gaining, losing, or sharing of electrons. The number and arrangement of electrons — especially outer (valence) electrons — determine how an atom reacts." },
  { difficulty:"easy", q:"Why does copper turn green over time?", options:["It rusts like iron","It reacts with oxygen and moisture to form copper carbonate (a green patina)","It absorbs paint from the environment","Copper was never truly orange — it starts green"], answer:"It reacts with oxygen and moisture to form copper carbonate (a green patina)", explanation:"The green layer on copper (like the Statue of Liberty) is a mixture of copper carbonate and copper hydroxide — products of the slow reaction with CO₂ and water in the air." },
  { difficulty:"easy", q:"What type of chemical bond forms when electrons are transferred between atoms?", options:["Covalent bond","Ionic bond","Metallic bond","Hydrogen bond"], answer:"Ionic bond", explanation:"Ionic bonds form when one atom donates electrons to another, creating oppositely charged ions that attract each other. In NaCl, sodium gives an electron to chlorine." },
  { difficulty:"easy", q:"Which gas is produced when an acid reacts with a metal carbonate?", options:["Oxygen","Hydrogen","Carbon dioxide","Nitrogen"], answer:"Carbon dioxide", explanation:"Acid + metal carbonate → salt + water + CO₂. For example: 2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂. The fizzing you see is CO₂ escaping." },
  { difficulty:"easy", q:"Why does bread dough rise?", options:["Gluten stretches indefinitely","Yeast produces carbon dioxide gas, creating bubbles in the dough","Baking soda absorbs water and expands","Heat causes flour to expand"], answer:"Yeast produces carbon dioxide gas, creating bubbles in the dough", explanation:"Yeast ferments sugars and releases CO₂ as a byproduct. The gas is trapped by the gluten network, causing the dough to rise. Heat later sets the structure." },
  { difficulty:"easy", q:"What is the main difference between an element and a compound?", options:["Elements are liquids; compounds are solids","An element contains only one type of atom; a compound contains two or more different elements chemically bonded","Compounds cannot be broken down; elements can","There is no difference"], answer:"An element contains only one type of atom; a compound contains two or more different elements chemically bonded", explanation:"Oxygen (O₂) is an element — only oxygen atoms. Water (H₂O) is a compound — hydrogen and oxygen atoms chemically bonded together in a fixed ratio." },

  /* ---------- MEDIUM ---------- */
  { difficulty:"medium", q:"How many protons does a carbon atom have?", options:["4","6","8","12"], answer:"6", explanation:"Carbon's atomic number is 6 — it always has 6 protons. Its most common isotope (C-12) also has 6 neutrons." },
  { difficulty:"medium", q:"What type of bond holds water molecules to each other?", options:["Ionic bond","Covalent bond","Hydrogen bond","Metallic bond"], answer:"Hydrogen bond", explanation:"Each water molecule has a slightly positive hydrogen end and slightly negative oxygen end. These opposites attract neighbouring molecules, forming hydrogen bonds — responsible for water's unusually high boiling point." },
  { difficulty:"medium", q:"What is the main product besides water when an acid neutralises a base?", options:["A salt","An oxide","A gas","An alcohol"], answer:"A salt", explanation:"Acid + base → salt + water. For example: HCl + NaOH → NaCl + H₂O. The 'salt' produced is always an ionic compound made from the acid's anion and the base's cation." },
  { difficulty:"medium", q:"Which element has the highest electronegativity?", options:["Oxygen","Chlorine","Fluorine","Nitrogen"], answer:"Fluorine", explanation:"Fluorine tops the Pauling electronegativity scale at 3.98 — it attracts electrons more strongly than any other element, which is why it forms the most reactive compounds." },
  { difficulty:"medium", q:"Approximately how many particles are in one mole of a substance?", options:["6.022 × 10²³","3.14 × 10¹⁰","9.81 × 10²⁴","1.602 × 10⁻¹⁹"], answer:"6.022 × 10²³", explanation:"Avogadro's number (6.022 × 10²³) is the number of atoms, molecules, or ions in one mole of any substance — a convenient bridge between atomic-scale and laboratory-scale quantities." },
  { difficulty:"medium", q:"What is the molar mass of water (H₂O)?", options:["10 g/mol","16 g/mol","18 g/mol","20 g/mol"], answer:"18 g/mol", explanation:"H has molar mass 1 g/mol, O has 16 g/mol. H₂O = (2 × 1) + 16 = 18 g/mol. This means 18 grams of water contains exactly one mole (6.022 × 10²³ molecules)." },
  { difficulty:"medium", q:"In the reaction 2H₂ + O₂ → 2H₂O, how many grams of water form if 4 g of H₂ reacts completely? (Molar masses: H₂ = 2, H₂O = 18)", options:["9 g","18 g","36 g","72 g"], answer:"36 g", explanation:"4 g H₂ ÷ 2 g/mol = 2 mol H₂. From stoichiometry, 2 mol H₂ produces 2 mol H₂O. Mass = 2 × 18 = 36 g." },
  { difficulty:"medium", q:"Can a compound contain both ionic and covalent bonds?", options:["No — a compound can only have one type of bond","Yes — for example, sodium hydroxide (NaOH) has an ionic Na–O bond and a covalent O–H bond","Yes, but only in organic compounds","No — bonds cannot be mixed"], answer:"Yes — for example, sodium hydroxide (NaOH) has an ionic Na–O bond and a covalent O–H bond", explanation:"NaOH: the Na⁺ and OH⁻ ions are held by an ionic bond, but within the hydroxide ion the O and H are joined by a covalent bond. Many polyatomic salts work this way." },
  { difficulty:"medium", q:"What is Le Chatelier's principle?", options:["Reactions always go to completion","Adding a catalyst shifts equilibrium to the right","A system at equilibrium adjusts to oppose any change imposed on it","Temperature has no effect on equilibrium"], answer:"A system at equilibrium adjusts to oppose any change imposed on it", explanation:"If you add a reactant, increase temperature, or change pressure, the equilibrium shifts to partially counteract the change. This is Le Chatelier's principle — essential for industrial chemistry." },
  { difficulty:"medium", q:"Adding a catalyst to a reaction already at equilibrium — what happens?", options:["The equilibrium shifts to produce more product","The equilibrium shifts to produce more reactant","Equilibrium is reached faster but its position does not change","The reaction stops"], answer:"Equilibrium is reached faster but its position does not change", explanation:"A catalyst lowers the activation energy of both the forward and reverse reactions equally, speeding up both. The equilibrium constant (and position) is unchanged — only the time to reach it shortens." },
  { difficulty:"medium", q:"What is the molar mass of sulfuric acid (H₂SO₄)? (H=1, S=32, O=16)", options:["49 g/mol","80 g/mol","98 g/mol","114 g/mol"], answer:"98 g/mol", explanation:"H₂SO₄: (2×1) + 32 + (4×16) = 2 + 32 + 64 = 98 g/mol." },
  { difficulty:"medium", q:"How does soap remove grease from your hands?", options:["It dissolves grease in water","Soap molecules have a water-loving head and an oil-loving tail, surrounding grease so water can rinse it away","It chemically breaks down fat molecules","It changes the pH to dissolve oils"], answer:"Soap molecules have a water-loving head and an oil-loving tail, surrounding grease so water can rinse it away", explanation:"Soap is amphiphilic — its hydrophobic tail buries into grease while the hydrophilic head faces outward into water. These soap-grease clusters (micelles) can then be rinsed away." },
  { difficulty:"medium", q:"Why does cooking change a raw egg from liquid to solid?", options:["The water evaporates completely","Heat causes proteins to denature and form a solid network","The fats crystallise at high temperature","The egg absorbs water from the pan"], answer:"Heat causes proteins to denature and form a solid network", explanation:"Heat breaks the weak bonds maintaining protein structure. The unfolded proteins tangle together and form new bonds, creating a solid mesh — a permanent, irreversible chemical change." },
  { difficulty:"medium", q:"What is the difference between an exothermic and an endothermic reaction?", options:["Exothermic reactions need heat to start; endothermic release it","Exothermic reactions release heat; endothermic reactions absorb heat","Exothermic only occur in labs; endothermic occur naturally","They are the same — heat is always conserved"], answer:"Exothermic reactions release heat; endothermic reactions absorb heat", explanation:"Exothermic (ΔH < 0): combustion, respiration. Endothermic (ΔH > 0): photosynthesis, dissolving ammonium nitrate. The terms come from Greek: 'exo' = out, 'endo' = within." },
  { difficulty:"medium", q:"Why does salt lower the freezing point of water?", options:["Salt makes water hotter","Salt ions disrupt the crystal lattice formation of ice, requiring a lower temperature to freeze","Salt absorbs heat from water as it dissolves","Salt reacts with water to release energy"], answer:"Salt ions disrupt the crystal lattice formation of ice, requiring a lower temperature to freeze", explanation:"Dissolved Na⁺ and Cl⁻ ions interfere with the orderly arrangement of water molecules needed to form ice. This 'freezing point depression' is why roads are salted in winter — seawater freezes at about −1.8°C." },
  { difficulty:"medium", q:"Which of these represents an oxidation reaction?", options:["A substance gains electrons","A substance gains hydrogen","A substance loses electrons","A substance decreases in charge"], answer:"A substance loses electrons", explanation:"OIL RIG: Oxidation Is Loss (of electrons), Reduction Is Gain (of electrons). When iron rusts, it loses electrons to oxygen — iron is oxidised." },
  { difficulty:"medium", q:"What is the functional group of an alcohol?", options:["–COOH","–CHO","–OH","–NH₂"], answer:"–OH", explanation:"Alcohols contain the hydroxyl group (–OH). Ethanol (CH₃CH₂OH) is the alcohol in drinks. –COOH is a carboxylic acid, –CHO is an aldehyde, –NH₂ is an amine." },
  { difficulty:"medium", q:"Balance the equation: Fe + O₂ → Fe₂O₃. What are the correct coefficients?", options:["2, 1, 1","4, 3, 2","2, 3, 1","1, 1, 2"], answer:"4, 3, 2", explanation:"4Fe + 3O₂ → 2Fe₂O₃. Check: Left: 4 Fe, 6 O. Right: 4 Fe (2×2), 6 O (2×3). Balanced." },

  /* ---------- HARD ---------- */
  { difficulty:"hard", q:"Which orbital subshell corresponds to the quantum number ℓ = 2?", options:["s","p","d","f"], answer:"d", explanation:"ℓ = 0 → s, ℓ = 1 → p, ℓ = 2 → d, ℓ = 3 → f. The d subshell has 5 orbitals and holds up to 10 electrons." },
  { difficulty:"hard", q:"What is the hybridisation of carbon in ethyne (HC≡CH)?", options:["sp","sp²","sp³","sp³d"], answer:"sp", explanation:"Each carbon in ethyne forms two sigma bonds (one C–C, one C–H) using sp hybrid orbitals. The remaining two unhybridised p-orbitals form the two π bonds of the triple bond." },
  { difficulty:"hard", q:"Which catalyst is used in the Haber process to synthesise ammonia?", options:["Platinum","Iron","Nickel","Vanadium pentoxide"], answer:"Iron", explanation:"The Haber process (N₂ + 3H₂ ⇌ 2NH₃) uses finely divided iron with promoters (K₂O, Al₂O₃) at ~450°C and 200 atm. About half the world's food supply depends on ammonia fertilisers made this way." },
  { difficulty:"hard", q:"What does a negative Gibbs free energy (ΔG < 0) indicate about a reaction?", options:["It is endothermic","It is exothermic","It is thermodynamically spontaneous","It has reached equilibrium"], answer:"It is thermodynamically spontaneous", explanation:"ΔG = ΔH − TΔS. A negative ΔG means the reaction releases usable free energy — it can proceed spontaneously. Note: spontaneous does not mean fast — it says nothing about rate." },
  { difficulty:"hard", q:"Which acid is produced in the greatest industrial quantity worldwide?", options:["Nitric acid","Hydrochloric acid","Sulfuric acid","Acetic acid"], answer:"Sulfuric acid", explanation:"Sulfuric acid (H₂SO₄) is made in greater quantities than any other industrial chemical, primarily by the Contact Process. It is used in fertilisers, batteries, metal processing, and pharmaceuticals." },
  { difficulty:"hard", q:"Calculate the pH of a 0.01 mol/L solution of hydrochloric acid (HCl).", options:["1","2","3","12"], answer:"2", explanation:"HCl is a strong acid — it fully dissociates. [H⁺] = 0.01 = 10⁻² mol/L. pH = −log[H⁺] = −log(10⁻²) = 2." },
  { difficulty:"hard", q:"An exothermic reaction has ΔH < 0 and ΔS < 0. At what temperatures is it spontaneous?", options:["All temperatures","High temperatures only","Low temperatures only","It is never spontaneous"], answer:"Low temperatures only", explanation:"ΔG = ΔH − TΔS. With ΔH negative and ΔS negative, ΔG = (−) − T(−) = (−) + T(+). At low T the negative ΔH dominates making ΔG negative (spontaneous). At high T, the +TΔS term dominates making ΔG positive (non-spontaneous)." },
  { difficulty:"hard", q:"What is the key difference between a Lewis acid and a Brønsted-Lowry acid?", options:["Lewis acids donate H⁺; Brønsted-Lowry acids accept electron pairs","Brønsted-Lowry acids donate H⁺; Lewis acids accept an electron pair from a base","They are identical concepts","Lewis acids only apply to organic molecules"], answer:"Brønsted-Lowry acids donate H⁺; Lewis acids accept an electron pair from a base", explanation:"Brønsted-Lowry definition: acid = H⁺ donor. Lewis definition: acid = electron-pair acceptor. The Lewis definition is broader — BF₃ is a Lewis acid but cannot donate H⁺." },
  { difficulty:"hard", q:"What is the difference between SN1 and SN2 substitution mechanisms?", options:["SN1 is one-step with two reactants; SN2 is two-step with one reactant","SN1 is a two-step mechanism with a carbocation intermediate; SN2 is a one-step concerted reaction with inversion of configuration","They are the same mechanism with different names","SN1 involves oxygen; SN2 involves nitrogen"], answer:"SN1 is a two-step mechanism with a carbocation intermediate; SN2 is a one-step concerted reaction with inversion of configuration", explanation:"SN1 (unimolecular): rate depends only on substrate; proceeds via stable carbocation intermediate; common with tertiary substrates. SN2 (bimolecular): nucleophile attacks as leaving group leaves in a single step; inverts stereochemistry (Walden inversion); favoured with primary substrates." },
  { difficulty:"hard", q:"For the reaction A → products, if doubling [A] quadruples the rate, what is the order with respect to A?", options:["Zero order","First order","Second order","Third order"], answer:"Second order", explanation:"Rate ∝ [A]ⁿ. If [A] doubles and rate quadruples (×4 = 2²), then n = 2. The reaction is second order with respect to A." },
  { difficulty:"hard", q:"Why do metals conduct electricity so well?", options:["Metal atoms are very large","Metals contain a 'sea' of delocalised electrons that move freely throughout the lattice","Metal ions are positively charged and attract current","Metal atoms share electrons only in pairs"], answer:"Metals contain a 'sea' of delocalised electrons that move freely throughout the lattice", explanation:"In metallic bonding, outer electrons are not tied to individual atoms but flow freely through the entire structure. An applied voltage causes these free electrons to drift as current — which is why metals are excellent conductors." },
  { difficulty:"hard", q:"Why does HF behave as a weak acid despite fluorine being the most electronegative element?", options:["Fluorine does not attract electrons strongly enough","The H–F bond is very strong, reducing the extent of dissociation in water","Fluorine repels water molecules","HF is actually a strong acid"], answer:"The H–F bond is very strong, reducing the extent of dissociation in water", explanation:"You might expect HF to be a strong acid, but the H–F bond is extremely short and strong (bond energy ~570 kJ/mol). Little of the HF dissociates into H⁺ and F⁻ in water — making it a weak acid, unlike HCl, HBr, and HI." },
  { difficulty:"hard", q:"What is a buffer solution and why does it resist pH change?", options:["A solution that prevents all chemical reactions","A solution containing a weak acid and its conjugate base that can neutralise small additions of acid or base","A solution of pure water kept at pH 7","A concentrated acid that absorbs base"], answer:"A solution containing a weak acid and its conjugate base that can neutralise small additions of acid or base", explanation:"Adding H⁺: the conjugate base neutralises it (A⁻ + H⁺ → HA). Adding OH⁻: the weak acid neutralises it (HA + OH⁻ → A⁻ + H₂O). Blood is buffered at pH 7.35–7.45 by the carbonic acid / bicarbonate system." },
  { difficulty:"hard", q:"Why does increasing pressure favour the reaction N₂ + 3H₂ ⇌ 2NH₃?", options:["Pressure has no effect on reactions involving gases","The forward reaction reduces the number of moles of gas (4 → 2), so higher pressure shifts equilibrium toward fewer moles","Pressure increases temperature, which speeds the reaction","Pressure breaks the N≡N triple bond directly"], answer:"The forward reaction reduces the number of moles of gas (4 → 2), so higher pressure shifts equilibrium toward fewer moles", explanation:"Le Chatelier's principle: increasing pressure favours the side with fewer moles of gas. Left side: 1 + 3 = 4 mol gas. Right side: 2 mol gas. So high pressure pushes the equilibrium right toward NH₃." },
  { difficulty:"hard", q:"What is a redox reaction and identify which species is oxidised in: Zn + CuSO₄ → ZnSO₄ + Cu?", options:["No redox occurs here; Zn is oxidised","Redox involves electron transfer; Cu²⁺ is oxidised","Redox involves electron transfer; Zn is oxidised (loses electrons to Cu²⁺)","Redox involves proton transfer; SO₄²⁻ is oxidised"], answer:"Redox involves electron transfer; Zn is oxidised (loses electrons to Cu²⁺)", explanation:"Zn → Zn²⁺ + 2e⁻ (oxidation: loses electrons). Cu²⁺ + 2e⁻ → Cu (reduction: gains electrons). Zinc displaces copper because it is higher in the reactivity series — a classic single displacement redox reaction." },
];

const BIOLOGY = [
  /* ---------- EASY ---------- */
  { difficulty:"easy", q:"What is the powerhouse of the cell?", options:["Nucleus","Ribosome","Mitochondrion","Golgi apparatus"], answer:"Mitochondrion", explanation:"Mitochondria generate most of the cell's ATP through cellular respiration, converting glucose and oxygen into usable energy." },
  { difficulty:"easy", q:"What process do plants use to make food from sunlight?", options:["Respiration","Photosynthesis","Fermentation","Transpiration"], answer:"Photosynthesis", explanation:"Plants convert CO₂ and water into glucose and oxygen using light energy absorbed by chlorophyll in chloroplasts: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂." },
  { difficulty:"easy", q:"How many chambers does a human heart have?", options:["2","3","4","5"], answer:"4", explanation:"The human heart has two atria (upper chambers that receive blood) and two ventricles (lower chambers that pump blood) — four in total." },
  { difficulty:"easy", q:"What is the basic unit of life?", options:["Atom","Molecule","Cell","Tissue"], answer:"Cell", explanation:"All living organisms are made of one or more cells — the smallest structure capable of carrying out all basic life functions independently." },
  { difficulty:"easy", q:"What is the largest organ in the human body?", options:["Liver","Brain","Heart","Skin"], answer:"Skin", explanation:"The skin (integumentary system) is the body's largest organ by surface area (~2 m²) and mass. It protects against pathogens, regulates temperature, and provides sensation." },
  { difficulty:"easy", q:"Is a virus alive?", options:["Yes — it reproduces","Yes — it has DNA","No — it cannot reproduce without hijacking a host cell","No — it has no carbon-based molecules"], answer:"No — it cannot reproduce without hijacking a host cell", explanation:"Viruses lack the cellular machinery to reproduce independently. They inject their genetic material into a host cell and use its ribosomes and enzymes to replicate — which is why most biologists consider them non-living." },
  { difficulty:"easy", q:"Starting from one cell dividing by mitosis twice, how many cells result?", options:["2","3","4","8"], answer:"4", explanation:"Each mitotic division doubles the cell count: 1 → 2 → 4. After two divisions you have four genetically identical cells." },
  { difficulty:"easy", q:"What type of biomolecule is an enzyme?", options:["Lipid","Carbohydrate","Protein","Nucleic acid"], answer:"Protein", explanation:"Enzymes are biological catalysts made of protein. Their specific three-dimensional shape (determined by amino acid sequence) allows them to bind substrates and speed up reactions without being consumed." },
  { difficulty:"easy", q:"Why do we shiver when we are cold?", options:["The body releases stored heat","Rapid muscle contractions generate heat","Shivering opens pores to absorb warmth","Blood stops flowing to the skin"], answer:"Rapid muscle contractions generate heat", explanation:"Shivering is an involuntary muscle activity controlled by the hypothalamus. The rapid contractions generate heat as a byproduct of ATP hydrolysis, helping to maintain core body temperature." },
  { difficulty:"easy", q:"Why is it important to complete a full course of antibiotics?", options:["Leftover antibiotics can be used for colds later","Stopping early can leave surviving, more resistant bacteria that multiply and cause a harder-to-treat infection","Antibiotics only work for exactly the prescribed number of days","To avoid the antibiotics turning into toxins"], answer:"Stopping early can leave surviving, more resistant bacteria that multiply and cause a harder-to-treat infection", explanation:"The bacteria most resistant to the antibiotic survive the longest. If you stop early, those hardy survivors reproduce, potentially creating a resistant strain — contributing to the global antibiotic resistance crisis." },
  { difficulty:"easy", q:"Why do leaves change colour in autumn?", options:["They absorb different wavelengths of sunlight","Chlorophyll breaks down, revealing yellow and orange pigments already present","Cold temperature adds red and orange dyes","Leaves produce new pigments in autumn as a defence against frost"], answer:"Chlorophyll breaks down, revealing yellow and orange pigments already present", explanation:"Green chlorophyll dominates in summer, masking other pigments. As daylight shortens, trees stop making chlorophyll. As it breaks down, the underlying carotenoids (yellow, orange) are revealed. Red anthocyanins are newly produced in some species." },
  { difficulty:"easy", q:"What is the difference between a chromosome and a gene?", options:["They are the same thing","A chromosome is made of many genes; a gene is a specific DNA sequence that codes for a protein","A gene contains many chromosomes","Chromosomes are made of RNA; genes are made of DNA"], answer:"A chromosome is made of many genes; a gene is a specific DNA sequence that codes for a protein", explanation:"Human cells have 46 chromosomes. Each chromosome is a long DNA molecule containing thousands of genes. A gene is a specific segment of DNA that carries the instructions for making a functional product (usually a protein)." },
  { difficulty:"easy", q:"Why does your heart rate increase during exercise?", options:["The heart is exercising too","Muscles demand more oxygen and glucose; the heart pumps faster to deliver them","Your body temperature drops, triggering the heart","Brain signals slow the digestive system and redirect blood"], answer:"Muscles demand more oxygen and glucose; the heart pumps faster to deliver them", explanation:"Working muscles consume oxygen rapidly and produce CO₂. Detected by chemoreceptors, this signals the cardiovascular centre in the medulla oblongata to increase heart rate and cardiac output." },
  { difficulty:"easy", q:"Can a human survive without a stomach?", options:["No — the stomach is essential for life","Yes — the small intestine can absorb nutrients after surgical removal, with dietary adjustments","No — without a stomach the body cannot produce blood","Yes — but only for a few weeks"], answer:"Yes — the small intestine can absorb nutrients after surgical removal, with dietary adjustments", explanation:"After a gastrectomy (full stomach removal), patients survive by eating small, frequent meals. The small intestine handles digestion and absorption. This is sometimes done as a treatment for stomach cancer or severe obesity." },
  { difficulty:"easy", q:"Which gas do humans exhale in greater quantities than they inhale?", options:["Oxygen","Nitrogen","Carbon dioxide","Water vapour"], answer:"Carbon dioxide", explanation:"Cellular respiration produces CO₂ as a waste product: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. We inhale air with ~0.04% CO₂ and exhale air with ~4% CO₂." },
  { difficulty:"easy", q:"What part of the plant absorbs water and minerals from the soil?", options:["Leaves","Stem","Roots","Flowers"], answer:"Roots", explanation:"Root hair cells increase the surface area for absorption. Water enters by osmosis; minerals are absorbed by active transport. The absorbed water and minerals travel up the stem via xylem vessels." },
  { difficulty:"easy", q:"Which blood type is known as the universal donor for red blood cells?", options:["Type A","Type B","Type AB","Type O negative"], answer:"Type O negative", explanation:"Type O negative red blood cells lack A, B, and Rh antigens — so they will not trigger an immune reaction in recipients of any blood type. In emergencies, O negative blood can be transfused before blood typing is possible." },
  { difficulty:"easy", q:"What is the role of red blood cells?", options:["Fight infection","Transport oxygen via haemoglobin","Produce antibodies","Regulate blood clotting"], answer:"Transport oxygen via haemoglobin", explanation:"Red blood cells (erythrocytes) contain haemoglobin, an iron-containing protein that binds oxygen in the lungs and releases it to tissues. Their biconcave shape maximises surface area for gas exchange." },

  /* ---------- MEDIUM ---------- */
  { difficulty:"medium", q:"Which molecule carries genetic information in most living organisms?", options:["RNA","DNA","Protein","Lipid"], answer:"DNA", explanation:"DNA (deoxyribonucleic acid) stores hereditary information as sequences of four bases: A, T, C, G. RNA is mainly involved in expressing that information (transcription and translation)." },
  { difficulty:"medium", q:"Which blood cells are the primary defenders against infection?", options:["Red blood cells","White blood cells","Platelets","Mast cells"], answer:"White blood cells", explanation:"White blood cells (leukocytes) — including neutrophils, lymphocytes, and macrophages — form the immune system's front line. They engulf pathogens, produce antibodies, and coordinate immune responses." },
  { difficulty:"medium", q:"Which scientist proposed the theory of evolution by natural selection?", options:["Mendel","Darwin","Pasteur","Watson"], answer:"Darwin", explanation:"Charles Darwin published 'On the Origin of Species' in 1859. He proposed that individuals with heritable traits better suited to their environment survive and reproduce more — driving evolution over generations." },
  { difficulty:"medium", q:"What part of the plant is the primary site of photosynthesis?", options:["Roots","Stem","Leaves","Flowers"], answer:"Leaves", explanation:"Leaves contain most of a plant's chloroplasts, arranged in the mesophyll layer. Their flat shape maximises surface area for light absorption while stomata allow gas exchange." },
  { difficulty:"medium", q:"During which phase of mitosis do chromosomes align at the cell's equator?", options:["Prophase","Metaphase","Anaphase","Telophase"], answer:"Metaphase", explanation:"In metaphase, chromosomes are maximally condensed and align along the metaphase plate (cell's equator). Spindle fibres attach to centromeres, ready to pull chromosomes to opposite poles in anaphase." },
  { difficulty:"medium", q:"All arteries carry oxygenated blood — true or false?", options:["True — arteries always carry oxygenated blood","False — the pulmonary artery carries deoxygenated blood from the heart to the lungs","True — veins carry deoxygenated blood so arteries must carry oxygenated","False — arteries carry blood in both directions"], answer:"False — the pulmonary artery carries deoxygenated blood from the heart to the lungs", explanation:"Arteries carry blood AWAY from the heart; veins carry blood TOWARD it. The pulmonary artery carries oxygen-poor blood from the right ventricle to the lungs. The pulmonary vein returns oxygenated blood to the heart." },
  { difficulty:"medium", q:"A species has a diploid chromosome number of 46. How many chromosomes are in each of its gametes?", options:["92","46","23","12"], answer:"23", explanation:"Gametes (sperm and egg) are haploid — they contain half the normal chromosome number. In humans, diploid = 46, so gametes have 23 chromosomes. Fertilisation restores 46." },
  { difficulty:"medium", q:"In Mendel's cross Tt × Tt, what fraction of offspring are expected to be homozygous recessive (tt)?", options:["1/4","1/2","3/4","0"], answer:"1/4", explanation:"Punnett square for Tt × Tt: TT : Tt : tt = 1 : 2 : 1. So 1/4 of offspring are expected to be homozygous recessive (tt) and show the recessive phenotype." },
  { difficulty:"medium", q:"What is the central dogma of molecular biology?", options:["Proteins make RNA, which makes DNA","DNA is transcribed to RNA, which is translated into protein","RNA is transcribed from protein, then converted to DNA","DNA is directly translated into protein"], answer:"DNA is transcribed to RNA, which is translated into protein", explanation:"Francis Crick's central dogma (1958): DNA → RNA → Protein. DNA is transcribed into mRNA in the nucleus; mRNA travels to ribosomes where it is translated into a specific amino acid sequence (protein)." },
  { difficulty:"medium", q:"Why is the small intestine so long (approximately 6–7 metres in adults)?", options:["To hold more food","To slow digestion down deliberately","To maximise the surface area available for nutrient absorption","To produce more digestive enzymes"], answer:"To maximise the surface area available for nutrient absorption", explanation:"The small intestine has three structural adaptations that increase surface area enormously: folds (plicae), finger-like villi, and microscopic microvilli (brush border) — collectively giving ~250 m² of absorptive surface." },
  { difficulty:"medium", q:"How do vaccines protect against disease?", options:["They kill pathogens already in your body","They stimulate the immune system to produce memory cells without causing full disease","They coat pathogens so white blood cells can see them","They increase body temperature to kill viruses"], answer:"They stimulate the immune system to produce memory cells without causing full disease", explanation:"Vaccines expose the immune system to an antigen (killed/weakened pathogen, protein, or mRNA instructions) triggering antibody production and immunological memory. On future exposure, the response is rapid and prevents disease." },
  { difficulty:"medium", q:"What is the difference between mitosis and meiosis?", options:["Mitosis produces gametes; meiosis produces body cells","Mitosis produces 2 genetically identical daughter cells; meiosis produces 4 genetically unique haploid cells","They are identical processes","Mitosis occurs only in plants; meiosis in animals"], answer:"Mitosis produces 2 genetically identical daughter cells; meiosis produces 4 genetically unique haploid cells", explanation:"Mitosis: growth, repair, asexual reproduction — 2 identical diploid cells. Meiosis: sexual reproduction — 4 genetically diverse haploid cells (gametes) through two rounds of division and crossing-over." },
  { difficulty:"medium", q:"Which organ produces insulin?", options:["Liver","Kidney","Pancreas","Adrenal gland"], answer:"Pancreas", explanation:"Beta cells in the islets of Langerhans within the pancreas produce insulin. Insulin enables cells to take up glucose from the blood, lowering blood glucose levels after a meal." },
  { difficulty:"medium", q:"Which body cell has the most DNA?", options:["A sperm cell","A red blood cell","Any typical body (somatic) cell","A platelet"], answer:"Any typical body (somatic) cell", explanation:"Most somatic cells are diploid (46 chromosomes). Red blood cells have no nucleus (no DNA). Sperm cells are haploid (23 chromosomes). So a regular body cell contains more DNA than a gamete." },
  { difficulty:"medium", q:"Why does the brain require a near-constant supply of glucose?", options:["The brain stores large amounts of glycogen","The brain cannot use fatty acids as fuel and has minimal glycogen reserves","Glucose is the only molecule that can cross the skull","The brain uses glucose only to produce heat"], answer:"The brain cannot use fatty acids as fuel and has minimal glycogen reserves", explanation:"Unlike muscles, the brain cannot oxidise fatty acids. It relies almost entirely on glucose. In starvation, the brain can adapt to use ketone bodies, but glucose is always preferred. A drop in blood glucose causes confusion, seizures, and coma." },
  { difficulty:"medium", q:"What is the function of the stomata on a leaf?", options:["Absorb light for photosynthesis","Allow gas exchange (CO₂ in, O₂ and water vapour out) and regulate water loss","Attract insects for pollination","Anchor the leaf to the stem"], answer:"Allow gas exchange (CO₂ in, O₂ and water vapour out) and regulate water loss", explanation:"Stomata are pores surrounded by guard cells that open during the day to let in CO₂ for photosynthesis (and release O₂ and water vapour). They close at night or during drought to prevent water loss." },
  { difficulty:"medium", q:"What is homeostasis?", options:["The process of cell division","The maintenance of a stable internal environment despite external changes","The digestion of food in the stomach","The transmission of nerve impulses"], answer:"The maintenance of a stable internal environment despite external changes", explanation:"Homeostasis keeps internal conditions (temperature, blood glucose, pH, water balance) within narrow limits. It operates through negative feedback loops — a sensor detects deviation, an effector corrects it. Examples: sweating, shivering, insulin release." },
  { difficulty:"medium", q:"What structure controls the passage of materials into and out of the cell?", options:["Cell wall","Nucleus","Cell membrane (plasma membrane)","Cytoplasm"], answer:"Cell membrane (plasma membrane)", explanation:"The selectively permeable phospholipid bilayer controls what enters and exits the cell — allowing small non-polar molecules to diffuse freely while regulating larger molecules and ions through protein channels and pumps." },

  /* ---------- HARD ---------- */
  { difficulty:"hard", q:"Which enzyme unwinds the DNA double helix during replication?", options:["DNA polymerase","Helicase","Ligase","Primase"], answer:"Helicase", explanation:"Helicase breaks the hydrogen bonds between complementary base pairs, separating the two strands to create a replication fork. DNA polymerase then synthesises new strands in the 5'→3' direction." },
  { difficulty:"hard", q:"What is the functional unit of the kidney?", options:["Alveolus","Neuron","Nephron","Hepatocyte"], answer:"Nephron", explanation:"Each kidney contains about one million nephrons. A nephron consists of a glomerulus (filtration), proximal tubule, loop of Henle (concentration), distal tubule, and collecting duct — collectively filtering ~180 litres of blood per day." },
  { difficulty:"hard", q:"Which part of the brain regulates balance and coordination of movement?", options:["Cerebrum","Cerebellum","Medulla oblongata","Hypothalamus"], answer:"Cerebellum", explanation:"The cerebellum at the rear of the brain receives input from muscles, joints, and the vestibular system, and fine-tunes motor output for smooth, coordinated movement. Damage causes ataxia (unsteady gait)." },
  { difficulty:"hard", q:"What molecule is the universal energy currency of cells?", options:["DNA","ATP","Glucose","NADH"], answer:"ATP", explanation:"Adenosine triphosphate (ATP) stores energy in its phosphate bonds. Hydrolysis (ATP → ADP + Pᵢ) releases ~30 kJ/mol of free energy to drive cellular work: muscle contraction, active transport, biosynthesis." },
  { difficulty:"hard", q:"During which phase of mitosis do chromosomes align at the cell's equator?", options:["Prophase","Metaphase","Anaphase","Telophase"], answer:"Metaphase", explanation:"In metaphase, chromosomes are maximally condensed and align along the metaphase plate. Spindle fibres from opposite poles attach to centromeres, ready to segregate chromosomes." },
  { difficulty:"hard", q:"A population of 100 bacteria doubles every 30 minutes. How many bacteria are present after 2 hours?", options:["400","800","1600","3200"], answer:"1600", explanation:"2 hours = 120 minutes = 4 doubling periods. N = 100 × 2⁴ = 100 × 16 = 1600 bacteria." },
  { difficulty:"hard", q:"What is the difference between competitive and allosteric (non-competitive) enzyme inhibition?", options:["They are identical in mechanism","Competitive inhibitors bind the active site and can be overcome by more substrate; allosteric inhibitors bind elsewhere, changing the enzyme shape permanently","Allosteric inhibition is reversible; competitive is not","Competitive inhibitors only inhibit at high temperatures"], answer:"Competitive inhibitors bind the active site and can be overcome by more substrate; allosteric inhibitors bind elsewhere, changing the enzyme shape permanently", explanation:"Competitive: inhibitor structurally mimics the substrate and competes for the active site — adding more substrate out-competes it (Vmax unchanged, Km increases). Allosteric: inhibitor binds a different site, inducing a conformational change that reduces activity — extra substrate cannot overcome this (Vmax decreases)." },
  { difficulty:"hard", q:"All mutations are harmful — true or false?", options:["True — any change to DNA causes disease","False — most mutations are neutral, some are beneficial, and evolution depends on heritable mutations","True — natural selection removes all mutations","False — only insertions and deletions are harmful; substitutions are harmless"], answer:"False — most mutations are neutral, some are beneficial, and evolution depends on heritable mutations", explanation:"Most mutations occur in non-coding DNA or cause synonymous codon changes with no effect (neutral). Beneficial mutations increase fitness — antibiotic resistance, sickle-cell trait providing malaria protection. Evolution by natural selection requires heritable variation, which mutations provide." },
  { difficulty:"hard", q:"In a cross between two parents who are both carriers (Aa) for a recessive condition, what is the probability of an affected child?", options:["0%","25%","50%","75%"], answer:"25%", explanation:"Carriers are Aa. Cross: Aa × Aa → AA (25%), Aa (50%), aa (25%). Only aa is affected (homozygous recessive) — 25% probability." },
  { difficulty:"hard", q:"Why do some bacteria become resistant to antibiotics so rapidly compared to humans developing drug resistance?", options:["Bacteria have larger genomes","Bacteria reproduce every 20–30 minutes and can transfer resistance genes horizontally between species","Bacteria produce more white blood cells","Bacteria can choose to mutate when threatened"], answer:"Bacteria reproduce every 20–30 minutes and can transfer resistance genes horizontally between species", explanation:"Bacteria can go through thousands of generations per day, rapidly selecting for resistant mutants. Additionally, horizontal gene transfer (plasmids carrying resistance genes) can spread resistance across different species almost instantaneously — a process impossible in sexually reproducing organisms." },
  { difficulty:"hard", q:"What is the difference between Type 1 and Type 2 diabetes?", options:["They are the same disease at different stages","Type 1 is autoimmune destruction of insulin-producing beta cells; Type 2 is insulin resistance in target cells","Type 1 affects adults; Type 2 affects children","Type 1 is caused by diet; Type 2 by genetics only"], answer:"Type 1 is autoimmune destruction of insulin-producing beta cells; Type 2 is insulin resistance in target cells", explanation:"Type 1 (5–10% of cases): the immune system destroys pancreatic beta cells — no insulin is produced. Requires insulin injections. Type 2 (90–95%): cells become resistant to insulin's signal; the pancreas compensates but eventually fails. Strongly linked to obesity and inactivity." },
  { difficulty:"hard", q:"What does the DNA sequence 5'-ATG-3' code for, and why is it significant?", options:["It codes for the amino acid leucine","ATG codes for methionine and serves as the universal start codon for translation","It codes for a stop signal — translation ends here","ATG codes for alanine in the first position only"], answer:"ATG codes for methionine and serves as the universal start codon for translation", explanation:"The codon AUG (ATG in DNA) codes for methionine in almost all living organisms. It signals the ribosome where to begin translating mRNA into protein. Every protein therefore starts with methionine (though it may be cleaved later)." },
  { difficulty:"hard", q:"What is the role of the myelin sheath around a neuron's axon?", options:["Provides nutrients to the axon","Increases the speed of nerve impulse transmission by allowing saltatory conduction","Connects the neuron to the next cell","Produces the action potential"], answer:"Increases the speed of nerve impulse transmission by allowing saltatory conduction", explanation:"Myelin (produced by Schwann cells in the PNS, oligodendrocytes in the CNS) insulates the axon with gaps called nodes of Ranvier. The action potential jumps between nodes (saltatory conduction), increasing speed from ~1 m/s to over 100 m/s. Multiple sclerosis involves demyelination." },
  { difficulty:"hard", q:"How does the CRISPR-Cas9 system edit genes?", options:["It uses X-rays to randomly mutate DNA","A guide RNA directs the Cas9 protein to a specific DNA sequence where it makes a precise double-strand cut, allowing deletion or insertion","It inserts genes using a viral vector only","It edits RNA, which then modifies DNA"], answer:"A guide RNA directs the Cas9 protein to a specific DNA sequence where it makes a precise double-strand cut, allowing deletion or insertion", explanation:"Cas9 is an endonuclease (DNA-cutting enzyme). A synthetic guide RNA (gRNA) is designed to match the target DNA sequence. The gRNA-Cas9 complex locates and cuts that specific sequence. The cell's repair machinery either disables the gene or inserts new DNA — enabling precise gene editing." },
  { difficulty:"hard", q:"The human body contains more bacterial cells than human cells — true or false?", options:["False — human cells vastly outnumber bacteria","True — there are approximately 38 trillion bacterial cells compared to ~30 trillion human cells","True — the ratio is 10:1 in favour of bacteria","False — bacteria only live on the skin surface"], answer:"True — there are approximately 38 trillion bacterial cells compared to ~30 trillion human cells", explanation:"A landmark 2016 paper (Sender et al.) revised the classic 10:1 estimate — the ratio is approximately 1.3:1. An average 70 kg man has ~30 trillion human cells and ~38 trillion bacteria, mostly in the colon. The gut microbiome plays crucial roles in immunity, digestion, and even mental health." },
  { difficulty:"hard", q:"What is epigenetics, and how does it differ from a genetic mutation?", options:["Epigenetics is the study of genes; mutations are errors in that study","Epigenetics involves heritable changes in gene expression without altering the DNA sequence itself, unlike mutations which change the sequence","Epigenetics only applies to plants","Mutations are temporary; epigenetic changes are permanent"], answer:"Epigenetics involves heritable changes in gene expression without altering the DNA sequence itself, unlike mutations which change the sequence", explanation:"Epigenetic changes — such as DNA methylation and histone modification — switch genes on or off without changing the underlying sequence. They can be influenced by environment (diet, stress, toxins) and can be inherited across generations. In contrast, mutations are permanent changes to the nucleotide sequence itself." },
];

const QUESTION_BANKS = { physics: PHYSICS, chemistry: CHEMISTRY, biology: BIOLOGY };

function getQuestions(subject, difficulty) {
  return QUESTION_BANKS[subject].filter(q => q.difficulty === difficulty);
}

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
